version: "3"
services:
    manager:
        build: ./manager
        depends_on:
            - db
        environment:
            CSV: data.csv
            USER: user
            MDP: password
            DATABASE: db
    
    db:
        image: postgres:latest
        environment:
            CSV: data.csv
            USER: user
            MDP: password
            DATABASE: db
    